// Code generated by errorz/gen_go.go; DO NOT EDIT.
package errorz

// Error represents a centralized error definition.
type Error struct {
	Code        string
	Msg         string
	Cause       string
	HTTPStatus  int
	Category    string
	Severity    string
	IsRetryable bool
	Solution    string
	Tags        []string
}

var (
	AU0001 = &Error{
		Code: "AU0001",
		Msg: "invalid credentials",
		Cause: "username or password incorrect",
		HTTPStatus: 401,
		Category: "business",
		Severity: "low",
		IsRetryable: false,
		Solution: "ask user to re-enter credentials",
		Tags: []string{
			"auth",
			"login",
		},
	}
	CM0000 = &Error{
		Code: "CM0000",
		Msg: "success",
		Cause: "operation completed successfully",
		HTTPStatus: 200,
		Category: "business",
		Severity: "low",
		IsRetryable: false,
		Solution: "no action needed",
		Tags: []string{
			"success",
		},
	}
	CM0400 = &Error{
		Code: "CM0400",
		Msg: "bad request",
		Cause: "invalid input or malformed request",
		HTTPStatus: 400,
		Category: "validation",
		Severity: "medium",
		IsRetryable: false,
		Solution: "check input format and required fields",
		Tags: []string{
			"client",
			"input",
		},
	}
	CM0500 = &Error{
		Code: "CM0500",
		Msg: "internal server error",
		Cause: "unexpected server-side error",
		HTTPStatus: 500,
		Category: "internal",
		Severity: "high",
		IsRetryable: true,
		Solution: "check logs and trace ID",
		Tags: []string{
			"server",
			"bug",
		},
	}
	PM0001 = &Error{
		Code: "PM0001",
		Msg: "insufficient balance",
		Cause: "user has not enough balance",
		HTTPStatus: 402,
		Category: "business",
		Severity: "medium",
		IsRetryable: false,
		Solution: "ask user to top-up or choose another method",
		Tags: []string{
			"payment",
			"balance",
		},
	}
	PM0002 = &Error{
		Code: "PM0002",
		Msg: "payment gateway timeout",
		Cause: "no response from payment gateway",
		HTTPStatus: 504,
		Category: "timeout",
		Severity: "high",
		IsRetryable: true,
		Solution: "retry after a short delay",
		Tags: []string{
			"payment",
			"timeout",
			"external",
		},
	}
)

var ErrorMap = map[string]*Error{
	"AU0001": AU0001,
	"CM0000": CM0000,
	"CM0400": CM0400,
	"CM0500": CM0500,
	"PM0001": PM0001,
	"PM0002": PM0002,
}
