// Code generated by errorz/gen_go.go; DO NOT EDIT.
package errz

import "fmt"

// Error represents a centralized error definition.
type Error struct {
	Domain      string
	Code        string
	Msg         string
	Cause       string
	Severity    string
	IsRetryable bool
}

func (e *Error) Error() string {
	return fmt.Sprintf("[Domain: %s] [Code: %s] Msg: %s | Cause: %s | Severity: %s | Retryable: %t",
		e.Domain, e.Code, e.Msg, e.Cause, e.Severity, e.IsRetryable)
}

var (
	AU0001 = &Error{
		Domain: "auth",
		Code: "AU0001",
		Msg: "invalid credentials",
		Cause: "username or password incorrect",
		Severity: "low",
		IsRetryable: false,
	}
	CM0000 = &Error{
		Domain: "common",
		Code: "CM0000",
		Msg: "success",
		Cause: "operation completed successfully",
		Severity: "low",
		IsRetryable: false,
	}
	CM0400 = &Error{
		Domain: "common",
		Code: "CM0400",
		Msg: "bad request",
		Cause: "invalid input or malformed request",
		Severity: "medium",
		IsRetryable: false,
	}
	CM0500 = &Error{
		Domain: "common",
		Code: "CM0500",
		Msg: "internal server error",
		Cause: "unexpected server-side error",
		Severity: "high",
		IsRetryable: true,
	}
	PM0001 = &Error{
		Domain: "payment",
		Code: "PM0001",
		Msg: "insufficient balance",
		Cause: "user has not enough balance",
		Severity: "medium",
		IsRetryable: false,
	}
	PM0002 = &Error{
		Domain: "payment",
		Code: "PM0002",
		Msg: "payment gateway timeout",
		Cause: "no response from payment gateway",
		Severity: "high",
		IsRetryable: true,
	}
)

